Add Bethesda latest Paid Creation Escape to Loot Masterlist
loot/starfield pull request #57
Opened 2024-08-23 20:08 UTC by DJLegends1011

2024-08-23 20:15 UTC, pStyl3 commented
Thanks for the PR. Please move the new entry inbetween `sfbgs00a_j.esm` and `sfbgs00e.esm`

2024-08-23 21:52 UTC, DJLegends1011 commented
will do!

2024-08-23 23:50 UTC, DJLegends1011 commented
and finished

2024-08-23 23:54 UTC, sibir-ine requested changes

2024-08-23 23:54 UTC, sibir-ine commented on masterlist.yaml
>    - name: 'sfbgs00e.esm'
There are some extra spaces here:

```suggestion
    group: *bgsCreationsGroup

  - name: 'sfbgs00e.esm'
```

2024-08-23 23:54 UTC, sibir-ine commented on masterlist.yaml
>  ###### Verified Creations ######
There are some extra newlines here:

```suggestion

###### Verified Creations ######
```

2024-08-24 01:17 UTC, sibir-ine approved these changes
Thanks!

2024-08-24 01:21 UTC, merged